name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s tests

      - name: Build and Deploy with ArgoCD
        run: |
          # Your build and deployment commands here
          # For example:
            docker build -t my-rest-api .
          # docker tag my-rest-api:latest your-docker-hub-account/my-rest-api:latest
          # docker push your-docker-hub-account/my-rest-api:latest
            argocd app sync my-app-name
          # Replace my-rest-api with your actual application name, and my-app-name with your ArgoCD application name
          # Make sure you have configured your Docker registry and ArgoCD properly
